name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CLI & SDK
        run: |
          mkdir -p $HOME/.geode/bin
          gh release download --repo geode-sdk/cli --pattern "*v*-linux.zip" --output $HOME/geode-cli.zip
          unzip $HOME/geode-cli.zip -d $HOME/.geode/bin
          chmod +x $HOME/.geode/bin/geode
          echo "$HOME/.geode/bin" >> $GITHUB_PATH
          $HOME/.geode/bin/geode sdk install
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Android
        run: |
          geode build -p android --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod-android
          path: build/*.geode
