name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Geode CLI
        run: |
          mkdir -p $HOME/.local/bin
          wget https://github.com/geode-sdk/cli/releases/download/v3.8.0/geode-cli-v3.8.0-linux.zip -O $HOME/geode.zip
          unzip $HOME/geode.zip -d $HOME/.local/bin
          chmod +x $HOME/.local/bin/geode
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Geode Profile & SDK
        run: |
          mkdir -p $HOME/fake-gd
          geode profile add --name default $HOME/fake-gd android64
          geode sdk install $HOME/geode-sdk

      - name: Build Mod
        run: |
          geode build -p android --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod-android
          path: build/*.geode

