name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CLI & SDK
        run: |
          wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip
          unzip geode-cli-linux.zip -d $HOME/.geode/bin
          echo "$HOME/.geode/bin" >> $GITHUB_PATH
          $HOME/.geode/bin/geode sdk install

      - name: Build Android
        run: |
          geode build -p android --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod-android
          path: build/*.geode
